In [74]:
import numpy as np
import random as random

import seaborn as sns
import matplotlib.pyplot as plt

import plotly.graph_objects as go
import plotly.figure_factory as ff

import matplotlib.path as mpltPath

Зададим комнату
Подбирать сетку взависимости от размеров комнаты
Координаты комнаты в метрах

In [244]:
nmayak = 4

xrooms1, yrooms1 = 0.5, 1.5
xrooms2, yrooms2 = 3.5, 1.5
xrooms3, yrooms3 = 3.5, 3.5
xrooms4, yrooms4 = 0.5, 3.5

kx = 0.1
ky = 0.1

rooms = [[xrooms1, yrooms1], [xrooms2, yrooms2],
         [xrooms3, yrooms3], [xrooms4, yrooms4]]

ncorner = len(rooms)

In [231]:
def createPoints(rooms, kx, ky):
    rooms = np.array(rooms)
    xmin = min(rooms[:, 0])
    xmax = max(rooms[:, 0])
    ymin = min(rooms[:, 1])
    ymax = max(rooms[:, 1])

    x = np.arange(xmin, xmax + kx, kx)
    y = np.arange(ymin, ymax + ky, ky)

    xx, yy = np.meshgrid(x, y)
    path = mpltPath.Path(rooms)

    points = []

    for i in range(len(xx)):
        for j in range(len(xx[i])):
            points.append([xx[i][j], yy[i][j]])

    inside2 = path.contains_points(points)

    pointsIn = []
    pointsOut = []

    for i in range(len(inside2)):
        flag = 0
        if inside2[i]:
            for j in range(len(rooms)):
                xc1, yc1 = rooms[j]
                if j != (ncorner - 1):
                    xc2, yc2 = rooms[j+1]
                else:
                    xc2, yc2 = rooms[0]

                x, y = points[i]

                k1 = abs(xc1 - xc2)
                k2 = abs(yc1 - yc2)
                s1  = np.sqrt(k1*k2 + k2*k2)

                k1 = abs(xc1 - x)
                k2 = abs(yc1 - y)
                s2  = np.sqrt(k1*k2 + k2*k2)

                k1 = abs(xc2 - x)
                k2 = abs(yc2 - y)
                s3  = np.sqrt(k1*k2 + k2*k2)

                s1 = np.round(s1*1e4)/1e-4
                s2 = s2 + s3
                s2 = np.round(s2*1e4)/1e-4

                if s2==s1:
                    flag = 1

            if flag == 1:
                pointsOut.append(points[i])
            else:
                pointsIn.append(points[i])

        else:
            pointsOut.append(points[i])

    pointsIn = np.array(pointsIn)
    pointsOut = np.array(pointsOut)

    return pointsIn, pointsOut

In [232]:
pointsIn, pointsOut = createPoints(rooms, kx, ky)

31 21


In [233]:
roomsPlot = rooms.copy()
roomsPlot.append(roomsPlot[0])
xr, yr = zip(*roomsPlot)

xin, yin = pointsIn[:, 0], pointsIn[:, 1]
xout, yout = pointsOut[:, 0], pointsOut[:, 1]

fig = go.Figure()
fig.add_trace(go.Scatter(x=xr, y=yr,
                         mode='lines',
                         name='path'))
fig.add_trace(go.Scatter(x=xin, y=yin,
                         mode='markers',
                         name='points in path'))

fig.add_trace(go.Scatter(x=xout, y=yout,
                         mode='markers', name='points out path'))

fig.show()

In [245]:
def createCoordMayak(pointsIn, nmayak):
    coordMayak = np.zeros((nmayak, 2))
    for i in range(nmayak):
        coordMayak[i] = random.choice(pointsIn)
    return coordMayak

In [246]:
coordMayak = createCoordMayak(pointsIn, nmayak)

In [247]:
coordMayak

array([[2.25, 2.45],
       [1.8 , 1.95],
       [2.55, 2.9 ],
       [3.2 , 2.8 ]])

In [240]:
def createPointsIndoors(coordayak, pointsIn, nmayak):
    index = []
    for i in range(len(pointsIn)):
        for j in range(nmayak):
            if pointsIn[i][0] == coordMayak[j][0] and pointsIn[i][1] == coordMayak[j][1]:
                index.append(i)
    pointsInMetka = np.delete(pointsIn, index, axis=0)
    return pointsInMetka

In [241]:
pointsInMetka = createPointsIndoors(coordMayak, pointsIn, nmayak)

In [242]:
pointsInMetka

array([[0.6, 1.6],
       [0.7, 1.6],
       [0.8, 1.6],
       ...,
       [3.2, 3.4],
       [3.3, 3.4],
       [3.4, 3.4]])

In [243]:
pointsIn

array([[0.6, 1.6],
       [0.7, 1.6],
       [0.8, 1.6],
       ...,
       [3.2, 3.4],
       [3.3, 3.4],
       [3.4, 3.4]])

In [ ]:
xc1

In [ ]:
def intersection_point(x, y, xm1, xm2, xc1, xc2):
    if min(xm1, xm2) <= x <= max(xm1, xm2) and min(xc1, xc2) <= x <= max(xc1, xc2) and \
            min(ym1, ym2) <= y <= max(ym1, ym2) and min(yc1, yc2) <= y <= max(yc1, yc2):

        flag = 1
    else:
        flag = 0
    return flag

In [ ]:
def intersection_segments(rooms, mayak, metka, ncorner):

    flag_metka = []

    xm1, ym1 = mayak
    xm2, ym2 = metka

    A1 = ym1 - ym2
    B1 = xm2 - xm1
    C1 = xm1 * ym2 - xm2 * ym1

    def intersection_point(x, y, xm1, xm2, xc1, xc2):
        if min(xm1, xm2) <= x <= max(xm1, xm2) and min(xc1, xc2) <= x <= max(xc1, xc2) and \
                min(ym1, ym2) <= y <= max(ym1, ym2) and min(yc1, yc2) <= y <= max(yc1, yc2):

            flag = 1
        else:
            flag = 0
        return flag

    for i in range(ncorner):

        flag = 0

        xc1, yc1 = rooms[i]
        if i != (ncorner - 1):
            xc2, yc2 = rooms[i+1]
        else:
            xc2, yc2 = rooms[0]

        A2 = yc1 - yc2
        B2 = xc2 - xc1
        C2 = xc1 * yc2 - xc2 * yc1

        if (B1*A2 - B2*A1) != 0 and A1 != 0:
            y = (C2*A1 - C1*A2) / (B1*A2 - B2*A1)
            x = (-C1 - B1*y) / A1
            flag = intersection_point(x, y)
        else:
            flag = 0

        if (B1*A2 - B2*A1) != 0 and A2 != 0:
            y = (C2*A1 - C1*A2) / (B1*A2 - B2*A1)
            x = (-C2 - B2*y) / A2
            flag = intersection_point(x, y)
        else:
            # пересечения отрезков нет, отрезки параллельны
            flag = 0

        flag_metka.append(flag)

    return max(flag_metka)