In [6]:
import random
import numpy as np

import matplotlib.pyplot as plt
import plotly.graph_objects as go
import plotly.figure_factory as ff

from functions import *

In [7]:
# задаем число маяков
nanchors = 4

# число углов комнаты
ncorners = 4

# шаг сетки
stepx = 0.1
stepy = 0.1

# массив координат по х и у
# xcoord = np.array((0.5, 4.5, 3.5, 0.5))
# ycoord = np.array((1.5, 2.5, 4.5, 3.5))

xcoord = np.array((0.5, 3.5, 3.5, 0.5))
ycoord = np.array((0.5, 0.5, 3.5, 3.5))

In [8]:
# формируем комнату
room = createRoom(xcoord, ycoord)
# формируем точки внутри помещения
pointsIn, pointsOut = createPoints(stepx, stepy, xcoord, ycoord)

# нормировка комнаты
roomScaler, pointsInScaler, pointsOutScaler, scaler = standardScalerPoints(xcoord, ycoord, pointsIn, pointsOut)
# нормировка по координатам
xcoordScaler = roomScaler[:, 0]
ycoordScaler = roomScaler[:, 1]

# генерируем координаты маяков
# можно не сравнивать со всеми точками внутри - т.к. места маяков не попадают на сетку
coordAnchorsScaler = createCoordAnchors(nanchors, xcoordScaler, ycoordScaler)

# подумать нужны ли те точки, которые мы хотим видеть pointsVisible
DOP = estimateDOP(roomScaler, pointsInScaler, coordAnchorsScaler, nanchors, DOPmax=20)

In [29]:
plotRoom(roomScaler, pointsInScaler, pointsOutScaler)
plotAnchors(coordAnchorsScaler, roomScaler)
plotDOPfactor(roomScaler, coordAnchorsScaler, DOP, pointsInScaler)

In [30]:
npopul = 30
nsurv = 15
nnew = npopul - nsurv
epohs = 20

In [31]:
popul = []
populMetka = []
val = []

plotMeanVal = []
plotMinVal = []

for i in range(npopul):
    bot = createCoordAnchors(nanchors, xcoordScaler, ycoordScaler)
    popul.append(bot)

for bot in popul[:5]:
    print(bot)

[[-0.75809174  0.33065824]
 [-0.02333161  0.11704497]
 [-0.18250276 -0.76064612]
 [ 0.91908667  0.78046643]]
[[ 0.61996978 -0.29303962]
 [-0.52973556  0.48601801]
 [-0.76353307  0.20657902]
 [ 0.97885415 -0.77949413]]
[[ 0.03014003 -0.9714521 ]
 [ 0.99448269 -0.90764005]
 [ 0.23711301 -0.22135488]
 [ 0.12469603  0.92223411]]
[[ 0.79450641  0.30707158]
 [ 0.11132769  0.99932176]
 [-0.16097109 -0.51473147]
 [ 0.69232295  0.14796561]]
[[-0.39447107  0.12881953]
 [ 0.0623425  -0.12171345]
 [ 0.7597597   0.60333443]
 [-0.63463582  0.00644815]]


In [32]:
val = []

for bot in popul:
    DOP = estimateDOP(roomScaler, pointsInScaler, bot, nanchors, DOPmax=20)
    val.append(sum(DOP) / len(DOP))

for res in val[:5]:
    print(res)

1.1268763603959004
1.2692035406571422
1.1893172109682348
1.2324416248269836
1.3298610555028165


In [33]:
sval = sorted(val, reverse=False)
for res in sval[:5]:
    print(res)

1.0996646768431337
1.1046863884609492
1.117457015171999
1.117653027458701
1.1238267223762581


In [34]:
newpopul, sval = getSurvPopul(popul, val, nsurv, reverse=0)

for i in range(nsurv):
    print(f'бот, {popul[i]},  результат, {sval[i]}')

бот, [[-0.75809174  0.33065824]
 [-0.02333161  0.11704497]
 [-0.18250276 -0.76064612]
 [ 0.91908667  0.78046643]],  результат, 1.0996646768431337
бот, [[ 0.61996978 -0.29303962]
 [-0.52973556  0.48601801]
 [-0.76353307  0.20657902]
 [ 0.97885415 -0.77949413]],  результат, 1.1046863884609492
бот, [[ 0.03014003 -0.9714521 ]
 [ 0.99448269 -0.90764005]
 [ 0.23711301 -0.22135488]
 [ 0.12469603  0.92223411]],  результат, 1.117457015171999
бот, [[ 0.79450641  0.30707158]
 [ 0.11132769  0.99932176]
 [-0.16097109 -0.51473147]
 [ 0.69232295  0.14796561]],  результат, 1.117653027458701
бот, [[-0.39447107  0.12881953]
 [ 0.0623425  -0.12171345]
 [ 0.7597597   0.60333443]
 [-0.63463582  0.00644815]],  результат, 1.1238267223762581
бот, [[-0.74306304 -0.91989586]
 [-0.69848801  0.90967023]
 [-0.18809738 -0.43361713]
 [ 0.30136083 -0.61772853]],  результат, 1.1268763603959004
бот, [[-0.82321665  0.94487144]
 [-0.98081746 -0.48022697]
 [ 0.55903688 -0.48559736]
 [ 0.6543027  -0.25971511]],  результат,

In [35]:
parent1, parent2 = getParents(newpopul, nsurv)
print('родитель 1', parent1)
print('родитель 2', parent2)

родитель 1 [[ 0.99985071  0.30223913]
 [ 0.26548976 -0.36694749]
 [-0.78274951 -0.45075954]
 [-0.01064348  0.63619588]]
родитель 2 [[ 0.03014003 -0.9714521 ]
 [ 0.99448269 -0.90764005]
 [ 0.23711301 -0.22135488]
 [ 0.12469603  0.92223411]]


In [36]:
idx = 4  # индекс гена
print('ген родителя_1', parent1.reshape(nanchors * 2)[idx])  # ген с индексом idx 1го родителя
print('ген родителя_2', parent2.reshape(nanchors * 2)[idx])  # ген с индексом idx 2го родителя

ген родителя_1 -0.7827495084330847
ген родителя_2 0.23711301480106783


In [37]:
# ген с индексом idx нового бота
gen_newbot = crossPointFrom2Parents(parent1.reshape(nanchors * 2), parent1.reshape(nanchors * 2), idx)
print('ген нового бота', gen_newbot)

ген нового бота -0.7827495084330847


In [38]:
mut = 0.25  # Коэфициент мутаций
print('ген нового бота от родителей', gen_newbot)

add_mut = mut * (2 * random.random() - 1.0)
print('слагаемое мутации в ген нового бота', add_mut)

gen_newbot += add_mut  # добавление слогаемого мутации
print('ген нового бота с мутацией', gen_newbot)

ген нового бота от родителей -0.7827495084330847
слагаемое мутации в ген нового бота -0.13933625285428858
ген нового бота с мутацией -0.9220857612873732


In [39]:
newbot = []  # пустой массив для нового бота

# проходимся по длине бота и осуществляем смешивание/скрещивание от родителей
for i in range(nanchors * 2):
    # Получаем значение для j-ого компонента бота
    gen_newbot = crossPointFrom2Parents(parent1.reshape(nanchors * 2), parent2.reshape(nanchors * 2), i)
    # Добавялем к значению бота случайную величину, зависящую от коэфециента мутации
    gen_newbot += mut * (2 * random.random() - 1.0)
    # Добавялем новое значение в бота
    newbot.append(gen_newbot)

print('новый бот', newbot)

новый бот [1.1568413275656333, -0.7547966540813085, 0.44474545395481224, -1.0952086603452034, -0.006330231789377583, -0.5176444887745245, -0.06286603125180285, 1.0383037403384834]


In [41]:
plotAnchors(np.array(newbot).reshape((nanchors, 2)), roomScaler)

In [42]:
def polyDistPoint(xanchor, yanchor, xcoord, ycoord):

    if (xcoord[0] != xcoord[-1]) or (ycoord[0] != ycoord[-1]):
        xcoord = np.append(xcoord, xcoord[0])
        ycoord = np.append(ycoord, ycoord[0])

    A = -np.diff(ycoord)
    B = np.diff(xcoord)
    C = ycoord[1:] * xcoord[:-1] - xcoord[1:] * ycoord[:-1]

    AB = 1 / (A ** 2 + B ** 2)
    vv = (A * xanchor + B * yanchor + C)
    xpoint = xanchor - (A * AB) * vv
    ypoint = yanchor - (B * AB) * vv

    idx_x = (((xpoint >= xcoord[:-1]) & (xpoint <= xcoord[1:])) | ((xpoint >= xcoord[1:]) & (xpoint <= xcoord[:-1])))
    idx_y = (((ypoint >= ycoord[:-1]) & (ypoint <= ycoord[1:])) | ((ypoint >= ycoord[1:]) & (ypoint <= ycoord[:-1])))
    idx = idx_x & idx_y

    dcoord = np.sqrt((xcoord[:-1] - xanchor) ** 2 + (ycoord[:-1] - yanchor) ** 2)

    if not any(idx):
        d = min(dcoord)
        i = np.argmin(dcoord)
        xpoly = xcoord[i]
        ypoly = ycoord[i]
    else:
        dpoint = np.sqrt((xpoint[idx] - xanchor) ** 2 + (ypoint[idx] - yanchor) ** 2)
        min_coord = min(dcoord)
        min_point = min(dpoint)
        i_coord = np.argmin(dcoord)
        i_point = np.argmin(dpoint)
        d = min(min_coord, min_point)
        i = np.argmin([i_coord, i_point])
        if i == 0:
            xpoly = xcoord[i_coord]
            ypoly = ycoord[i_coord]
        elif i == 1:
            idxs = np.where(idx)[0]
            xpoly = xpoint[idxs[i_point]]
            ypoly = ypoint[idxs[i_point]]

    return xpoly, ypoly

In [43]:
botn = np.array(newbot).reshape((nanchors, 2))

In [44]:
plotAnchors(botn, roomScaler)

In [55]:
botnn = []
path = pltPath.Path(roomScaler)
for bot in botn:
    inside = path.contains_points(bot.reshape((1,2)))
    print(inside)
    if not inside:
        xpoly, ypoly = polyDistPoint(bot[0], bot[1], xcoordScaler, ycoordScaler)
        botnn.append([xpoly, ypoly])
    else:
        botnn.append([bot[0], bot[1]])
botnn = np.array(botnn)

[False]
[False]
[ True]
[False]


In [46]:
plotAnchors(botnn, roomScaler)

In [51]:
botnn

array([[ 1.        , -0.75479665],
       [ 0.44474545, -1.        ],
       [-0.00633023, -0.51764449],
       [-0.06286603,  1.        ]])

In [47]:
path = pltPath.Path(roomScaler)

In [48]:
inside2 = path.contains_points(botnn)
inside2

array([ True, False,  True,  True])

In [49]:
inside2 = path.contains_points(botn)
inside2

array([False, False,  True, False])

In [50]:
botn

array([[ 1.15684133, -0.75479665],
       [ 0.44474545, -1.09520866],
       [-0.00633023, -0.51764449],
       [-0.06286603,  1.03830374]])

In [53]:
# подумать нужны ли те точки, которые мы хотим видеть pointsVisible
DOP = estimateDOP(roomScaler, pointsInScaler, coordAnchorsScaler, nanchors, DOPmax=20)

In [54]:
plotRoom(roomScaler, pointsInScaler, pointsOutScaler)
plotAnchors(botnn, roomScaler)
plotDOPfactor(roomScaler, botnn, DOP, pointsInScaler)